### ISSUE TITLE
Stop being so British

### ISSUE THREAD

**Issue by adam-zhang-nvcc** [NoodleBirb/Incremental-Haven#2]
https://github.com/NoodleBirb/Incremental-Haven/blob/8cf5ce27d54ced755877287c742bb97e98c247c5/Assets/Scripts/MainWorldScripts/Item.cs#L53

How dare you spell defense the NON AMERICAN WAY :eagle: :eagle: :fire: :bomb: :boom:

This is the LAND OF THE FREE :eagle: 

I demand that this be fixed at ONCE!!!! Unplayable otherwise.

**Comment by Fadoraaaaa** [comment]
IM PRRROUDDDDD TO BE AN AMERICANNNNNN RAHHHHHH ✊✊🔥🔥🔥🔥🦅🦅🦅💥💥 GOD BLESS AMERICA HOME OF THE BRAVE LAND OF THE FREEEEEEE

**Comment by ironon** [comment]
RAHHH 'MURICA 💣 🇺🇸 🦅 
GET THOSE DANG COMMUNIST UNAMERICAN FREEDOMLESS MCDONALDLESS "O PISH POSH" BEANS ON TOAST SPELLINGS OUT OF MY COUNTRY 😤😤😤💪💪💪
