### ISSUE TITLE
not working on my machine

### ISSUE THREAD

**Issue by Jupyner** [NoodleBirb/Incremental-Haven#3]
Specs:

- Operating System: Arch Linux 64-bit with Gnome version 47
- Processor: AMD Ryzen™ 5 5500U with Radeon™ Graphics × 12

I opened this up on Unity on my machine and it's giving me an error upon compiling.

`Assets/Scripts/MainWorldScripts/InteractableItem.cs(6,48): error CS0246: The type or namespace name 'InteractableObject' could not be found (are you missing a using directive or an assembly reference?)`

PLEASE FIX, I need this program as part of my daily workflow.

**Comment by NoodleBirb** [comment]
should be fixed now
